name: Node.js CI

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
